WahBuildBoot Alpha 2

diff --git a/wbb b/wbb
--- a/wbb
+++ b/wbb
@@ -4,19 +4,19 @@ CONFIG=$1/InfoWBB
 
 function mkroot {
 	echo -e "\e[0;31mDownloading files for new root...\e[0m"
-	echo "New Root:" /tmp/WBB_$Name/$Squash_root
+	echo "New Root:" $Files/Work/$Squash_root
 	if [ -d $Files/$Squash_root ]; then
-		cp -rv $Files/$Squash_root /tmp/WBB_$Name/$Squash_root
+		cp -rv $Files/$Squash_root $Files/Work/$Squash_root
 	else
 		echo -e "\e[1;31mERROR: \e[1;37m'$Files/$Squash_root'\e[0m don't exist."
 		exit 1
 	fi
-	echo "pacstrap /tmp/WBB_$Name/$Squash_root ${Packages[@]}"
+	echo "pacstrap $Files/Work/$Squash_root ${Packages[@]}"
 }
 
 function mksquash {
 	echo -e "\e[0;32mCreating SquashFS...\e[0m"
-	mksquashfs /tmp/WBB_$Name/$Squash_root /tmp/WBB_$Name/$Squash_name.sfs -comp xz
+	mksquashfs $Files/Work/$Squash_root $Files/Work/$Squash_name.sfs -comp xz
 }
 
 function mkiso {
@@ -26,21 +26,22 @@ function mkiso {
 	fi
 	mkdir -p $Files/$Output_directory
 	if [ -d $Files/$ISOFS ]; then
-		cp -rv $Files/$ISOFS /tmp/WBB_$Name
+		cp -rv $Files/$ISOFS $Files/Work
 	else
 		echo -e "\e[1;31mERROR: \e[1;37m'$Files/$ISOFS'\e[0m don't exist."
 		exit 1
 	fi
-	if [ -f /tmp/WBB_$Name/$Squash_name.sfs ];then
-                echo "SquashFS: /tmp/WBB_$Name/$Squash_name.sfs"
-                mv -v /tmp/WBB_$Name/$Squash_name.sfs /tmp/WBB_$Name/$ISOFS
+	if [ -f $Files/Work/$Squash_name.sfs ];then
+                echo "SquashFS: $Files/Work/$Squash_name.sfs"
+                mv -v $Files/Work/$Squash_name.sfs $Files/Work/$ISOFS
         else
-                echo -e "\e[1;31mERROR: \e[1;37m'/tmp/WBB_$Name/$Squash_name.sfs'\e[0m don't exist."
-                exit
+                echo -e "\e[1;31mERROR: \e[1;37m'$Files/Work/$Squash_name.sfs'\e[0m don't exist."
+		echo "Execute mksquashfs before or add your own SquashFS in $Files/Work named $Squash_name.sfs."
+                exit 1
         fi
 
-	mkisofs -o $Files/$Output_directory/$ISO_Output.iso -b $BIOS_Boot -c boot/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -R -J -V "$ISO_Label" /tmp/WBB_$Name/$ISOFS
-	echo -e "\nOutput: $Files/$Output_directory/$ISO_Output.iso\nBIOS Boot Image: $BIOS_Boot\nImage Label: $ISO_Label\nBase for image file system: $Files/$ISOFS\nImage file system: /tmp/WBB_$Name/$ISOFS"
+	mkisofs -o $Files/$Output_directory/$ISO_Output.iso -b $BIOS_Boot -c boot/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -R -J -V "$ISO_Label" $Files/Work/$ISOFS
+	echo -e "\nOutput: $Files/$Output_directory/$ISO_Output.iso\nBIOS Boot Image: $BIOS_Boot\nImage Label: $ISO_Label\nBase for image file system: $Files/$ISOFS\nImage file system: $Files/Work/$ISOFS"
 }
 
 echo -e "\e[38;5;202mWah Build Boot\e[0m"
@@ -53,10 +54,10 @@ fi
 if [ -n "$1" ]; then
 	if [ -f "$CONFIG" ]; then
 		source $CONFIG
-		if [ -d /tmp/WBB_$Name ]; then
-			rm -rvf /tmp/WBB_$Name
+		if [ -d $Files/Work ]; then
+			rm -rvf $Files/Work
 		fi
-		mkdir /tmp/WBB_$Name
+		mkdir $Files/Work
 		if [ -n "$2" ]; then
 			$2
 		else
